CREATE TABLE Book (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  YEAR_OF_PUBLISH INT NOT NULL,
  PRICE DECIMAL(10, 2) NOT NULL,
  CLASSIFICATION VARCHAR(255) NOT NULL,
  IS_AVAILABLE BOOLEAN NOT NULL
);